### ISSUE TITLE
Cannot read properties of underned (reading 'keywords')

### ISSUE THREAD

**Issue by JDubb-At-Nelnet** [halcyon-tech/vscode-rpgle#115]
Description of issue:
Linting not happening for a specific SQLRPGLE member that compiles just fine.  Linter works fine on other members.

extension version: V0.9.7
VSCODE version: 1.70.0
 
output:
```
Congratulations, your extension "vscode-rpgle" for desktop is now active!
vscode-rpgle language tools enabled.
vscode-rpgle linter enabled.
Error parsing /RDGJWEIRIC/QRPGLESRC/KFKCNSBNKR.SQLRPGLE: Cannot read properties of undefined (reading 'keywords')
TypeError: Cannot read properties of undefined (reading 'keywords')
	at e.getDocs (c:\Users\jweirich\.vscode\extensions\halcyontechltd.vscode-rpgle-0.9.7\dist\extension.js:1:39464)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.provideDocumentSymbols (c:\Users\jweirich\.vscode\extensions\halcyontechltd.vscode-rpgle-0.9.7\dist\extension.js:1:48300)
	at async a.provideDocumentSymbols (c:\Users\jweirich\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:37442)

```

**Comment by worksofliam** [comment]
@JDubb-At-Nelnet i will need the code, or a sample, to recreate the issue. Thanks!

**Comment by worksofliam** [comment]
@JDubb-At-Nelnet Will look into it ASAP.

**Comment by JDubb-At-Nelnet** [comment]
strangely, This error occurred when I was editing the source in a filesystem member.  when I ran CPYTOSTMF to put it in an IFS file and created a lint config in the working directory, it worked fine.  Then it seemed like it worked for a bit in the source member, but after a while the error came back.

**Comment by JDubb-At-Nelnet** [comment]
actually, now its a different error:

`Uri remote path: {"$mid":1,"fsPath":"\\RDGJWEIRIC\\QRPGLESRC\\KFKCNSBNKR.SQLRPGLE","_sep":1,"external":"member:/RDGJWEIRIC/QRPGLESRC/KFKCNSBNKR.SQLRPGLE","path":"/RDGJWEIRIC/QRPGLESRC/KFKCNSBNKR.SQLRPGLE","scheme":"member"}
Current path: RDGJWEIRIC/vscode/rpglint.JSON
Error linting /home/jweiric9/kfkcnsbnkr.sqlrpgle: Cannot read properties of undefined (reading 'options')
TypeError: Cannot read properties of undefined (reading 'options')
	at e.refreshDiagnostics (c:\Users\jweirich\.vscode\extensions\halcyontechltd.vscode-rpgle-0.9.7\dist\extension.js:1:62127)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
Current path: RDGJWEIRIC/VSCODE/RPGLINT.JSON`

**Comment by rishabkshk** [comment]
I am getting the same error as discussed in the original issue.

Error parsing /XXXXXSRC/QXXXROE/XXXXXX.SQLRPGLE: Cannot read properties of undefined (reading 'keywords')
TypeError: Cannot read properties of undefined (reading 'keywords')
	at e.getDocs (c:\Users\XXX\.vscode\extensions\halcyontechltd.vscode-rpgle-0.9.6\dist\extension.js:1:38878)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.provideDocumentSymbols (c:\Users\xxxxxxx\.vscode\extensions\halcyontechltd.vscode-rpgle-0.9.6\dist\extension.js:1:47714)
	at async a.provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:37442)
	
As @JDubb-At-Nelnet mentions, the linting works fine if the source is an IFS streamfile but not when it is a member.

**Comment by worksofliam** [comment]
@rishabkshk If you could share an example, that'd be great. Thank you!

**Comment by worksofliam** [comment]
@JDubb-At-Nelnet No errors for me so far. I am also going to need those two copy members from the source.

**Comment by worksofliam** [comment]
Solved in a fix. Will be out tonight.

**Comment by m-tyler** [comment]
Your comment mentions a fix coming out but in 0.9.8 I don't see this issue reported as fixed.  Did a fix make it into that version?   I am at 0.9.8 and I still see these issues.  I have a source that reproduces this issue.  For me, the issue appears in some copybook members.   The one that is the biggest issue is **FREE member with a special /IF DEFINED compile section. 

With that code commented out.
![image](https://user-images.githubusercontent.com/1353665/185664546-47fd346a-9fa0-413f-a016-5e0cb2610127.png)

With the commented section activated again.
![image](https://user-images.githubusercontent.com/1353665/185665028-09786600-66e8-4bfc-94aa-f33aad147108.png)

**Comment by worksofliam** [comment]
@m-tyler Are you able to paste that code here? That'll allow me to create a unit test for it. Thanks!

**Comment by m-tyler** [comment]
Sorry I was going to but got into paying around with possible reasons.  The basic reason is the parser doesn't like that the DS is defined across several lines.   If you comment out the /IF+/ENDIF defines the parser errors.  If you comment out the stand-alone semi-colon and add a semi-colon to the Template line it starts working. 

```
**FREE
// Function Return Param Definitions
Dcl-Ds Prp00a Qualified;
/IF DEFINED(PRP00A_TEMPLATE_ALL_DS)
 Template
/ENDIF
;
  Address Char(220);
  Emp Packed(6);
  Empname Char(60);
  Phone_w_errm Char(95);
  Phone Char(15) Overlay(Phone_w_errm :1);
  Zipcode_w_errm Char(90);
  Zipcode Char(10) Overlay(Zipcode_w_errm :1);
End-Ds;

Dcl-Ds Tmplt_EmpFmtAddress Qualified Template;
  Name Char(60);
  Addr1 Char(40);
  Addr2 Char(40);
  Addr3 Char(40);
  Addr4 Char(40);
End-Ds;
```

**Comment by m-tyler** [comment]
If that syntax is too complex for the parser to work with can it at least not break the outline and just not add that item to the outline?

**Comment by JDubb-At-Nelnet** [comment]
I'm still getting similar errors on v0.9.8.  I'll send the requested copylibs in case that helps.  Could have something to do with the copylibs NOT being free form while the main source IS fully free form.  This is a perfectly valid thing to do, mixing fixed copylibs with free form module / program source - but I could see that being difficult for the parser if it is parsing from copylibs too.

*edit* I tried commenting out the copylibs, saving, reopening, clearing output - still getting the errors.  Latest error:

````
Error parsing /RDGJWEIRIC/QRPGLESRC/KFKCNSBNKR.SQLRPGLE: Cannot read properties of undefined (reading 'toUpperCase')
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
	at Function.expandKeywords (c:\Users\jweirich\.vscode\extensions\halcyontechltd.vscode-rpgle-0.9.8\dist\extension.js:1:39896)
	at e.getDocs (c:\Users\jweirich\.vscode\extensions\halcyontechltd.vscode-rpgle-0.9.8\dist\extension.js:1:39535)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.provideDocumentSymbols (c:\Users\jweirich\.vscode\extensions\halcyontechltd.vscode-rpgle-0.9.8\dist\extension.js:1:48307)
	at async a.provideDocumentSymbols (c:\Users\jweirich\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:37442)
```

**Comment by worksofliam** [comment]
@JDubb-At-Nelnet Please send me another example to the same email you used before and I will look into it right away.

**Comment by worksofliam** [comment]
@m-tyler I put in a fix for the issue you were facing. Thanks for the example you provided.

**Comment by rishabkshk** [comment]
@worksofliam Hi Barry, how long will it take the fix to be in the new release?

**Comment by worksofliam** [comment]
For the original issue, maybe it will be out today. For the other issues, later this week.

**Comment by rishabkshk** [comment]
> For the original issue, maybe it will be out today. For the other issues, later this week.

Thanks Barry, 

I appreciate you making such a nice extension and actively maintaining it. For the issue related to `IF directive` with copybooks, sorry I was not able to provide you the code. I have updated my extension with yesterday's update but still facing the issue, may be the later update this week will fix the issue. 

I have the code now and if you can test your new changes with it, that would be helpful. Let me know the results.

**Main program**
`**FREE
/copy copysrc,variableds`

**copybook content**
`d someDs          ds                                                               
 /IF DEFINED(RPGBNV)                                                               
d                                     based(somepointer)                          
 /ENDIF                                                                            
d  xxxxxx  				        10i 0  
d  xxxxxxxx				        10i 0  
d  xxxxxx  				        20i 0  
d  xxx     				        10i 0  
d  xxxxx   				        10i 0  
d  yyyyy   				        10i 0  
d  zzzzz   				        10i 0  
d  fffffff 				          N    
d  jjjjj   				          N    
d  jjjjjjj 				          N    
d  mmmmm   				        10
d  cccccc  				         3
d  bbbbbbd 				        10i 0  
d  dddd    				        10i 0  
d  ddddd   				        10i 0  
d  bbbbb   				        10i 0  
d  ccc     				        10i 0  
d  bbbwee  				         7
d  fffbb   				        10i 0  
d  ff      				      1024a   `

Error log:

`Error parsing /XXXXXXX/QXXXXXX/PGMTEST.SQLRPGLE: Cannot read properties of undefined (reading 'keywords')
TypeError: Cannot read properties of undefined (reading 'keywords')
	at e.getDocs (c:\Users\USERNAME\.vscode\extensions\halcyontechltd.vscode-rpgle-0.10.0\dist\extension.js:1:40512)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.provideDocumentSymbols (c:\Users\USERNAME\.vscode\extensions\halcyontechltd.vscode-rpgle-0.10.0\dist\extension.js:1:49385)
	at async a.provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:37442)`

**Comment by rishabkshk** [comment]
Hi Barry,

You must have received my mail from a github comment.
I am attaching the program and copybook content for you to test.

Thanks
Rishab

**Comment by worksofliam** [comment]
Hi @rishabkshk I am still waiting for the file to come through. Send it to `liama@business.com` where `business` is my employer. Thanks!
